backend:
  name: github
  repo: mhamalgporee-ctrl/mhamalgporee-ctrl.github.io
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "المقالات والأشعار"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "التاريخ", name: "date", widget: "datetime"}
      - {label: "المحتوى", name: "body", widget: "markdown"}
